dist: focal

language: go

install:
- sudo apt-get update
- sudo apt-get install --reinstall ca-certificates

before_script:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=__coverage.cov -coverpkg=./... ./...
- $HOME/gopath/bin/goveralls -coverprofile=__coverage.cov -service=travis-ci
- docker build .
