dist: focal

language: go

before_script:
- sudo apt update && sudo apt install --yes --reinstall ca-certificates
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v -covermode=count -coverprofile=__coverage.cov -coverpkg=./... ./...
- $HOME/gopath/bin/goveralls -coverprofile=__coverage.cov -service=travis-ci
- docker build .
