dist: focal

language: go

go:
- 1.20

addons:
  apt:
    update: true
    packages: ca-certificates

before_script:
- go install golang.org/x/tools/cmd/cover@latest
- go install github.com/mattn/goveralls@latest

script:
- go test -v -covermode=count -coverprofile=__coverage.cov -coverpkg=./... ./...
- $HOME/gopath/bin/goveralls -coverprofile=__coverage.cov -service=travis-ci
- docker build .
