// Package api defines the datatype generated by this tool.
package api

// CmdOut defines the executed command line (including all flags and
// parameters) and the output it generated.
type CmdOut struct {
	Name        string
	CommandLine string
	Output      string
}

// NodeInfoV1 defines the list of executed commands and their outputs.
type NodeInfoV1 struct {
	CommandOutput []CmdOut `json:"command_output"`
}
